name: sive_calculator
description: "Una calculadora científica moderna e inteligente por Sive Tech Solutions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  math_expressions: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# CONFIGURACIÓN DEL ICONO (Sive Tech Solutions)
# Se consolidó para soportar iconos adaptativos (circulares/cuadrados)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  # Configuración para que el icono se adapte a cualquier forma de celular
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icon.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/